services:
  post-ms:
    build:
      context: ./post-ms
      dockerfile: Dockerfile
    ports:
      - 3001:3001

  user-ms:
    build:
      context: ./user-ms
      dockerfile: Dockerfile
    ports:
      - 3002:3002

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - post-ms
      - user-ms
